### ISSUE TITLE
Missing "DYNAMIC" OpenIdConnectApplicationIssuerMode

### ISSUE THREAD

**Issue by MasterSergius** [okta/okta-management-openapi-spec#121]
As per docs https://developer.okta.com/docs/reference/api/apps/#settings-10, which is also proved by issues: https://github.com/okta/okta-sdk-python/issues/286 and https://github.com/okta/okta-sdk-python/issues/287, openapi spec is missing "DYNAMIC" OpenIdConnectApplicationIssuerMode: https://github.com/okta/okta-management-openapi-spec/blob/master/resources/spec.yaml#L13742

**Comment by monde** [comment]
This issue was filed against our old Swagger spec that we maintained by hand and has been deprecated. The Swagger spec will not be updated and I'll close this issue.

We do have OpenAPI v3 specs for Okta's Management API, OAuth API, and IDP / My Account API in the [dist/](dist/) directory. These specs are derived directly from internal sources used to build and run the Okta service.

* Latest OpenAPI spec dist/current/
* [2024.06.1 Okta release](https://developer.okta.com/docs/release-notes/2024-okta-identity-engine/) (e.g. Latest/Current) OpenAPI spec [dist/2024.06.1/](dist/2024.06.1/)
* Historical Swagger spec [dist/legacy-v1-swagger/](dist/legacy-v1-swagger/)

Please open a support ticket at https://support.okta.com/ if you find one of the specs not working with your tooling to get help from a customer support engineer.
