### ISSUE TITLE
ApplicationSettingsApplication missing from API Spec

### ISSUE THREAD

**Issue by enfont** [okta/okta-management-openapi-spec#147]
Hi!

As described in this linked [issue](https://github.com/okta/okta-sdk-python/issues/312), when we recover a SAML_2_0 properties with some Applications Settings Application set (in our case the important field is companyId) the SDK returns an empty dict.

When we call the API directly we are getting the properties properly, but when using the SDK, app properties are blank.

GET {{url}}/api/v1/apps/{{app_id}}
```
    "settings": {
        "app": {
            "environment": "com",
            "companyId": "/id/test"
        },
```

As we can see in the [API Spec](https://github.com/okta/okta-management-openapi-spec/blob/master/resources/spec.yaml#L9681), the properties of this ApplicationSettingsApplication definition are not present.

Can you please take a look and fix it if possible? 

You have plenty of details in the linked issue in Python SDK https://github.com/okta/okta-sdk-python/issues/312

Thanks

**Comment by laura-rodriguez** [comment]
Thanks for reporting this! I've filed an internal issue to be reviewed and prioritized accordingly.

Internal Ref: OKTA-543278

**Comment by monde** [comment]
This issue was filed against our old Swagger spec that we maintained by hand and has been deprecated. The Swagger spec will not be updated and I'll close this issue.

We do have OpenAPI v3 specs for Okta's Management API, OAuth API, and IDP / My Account API in the [dist/](dist/) directory. These specs are derived directly from internal sources used to build and run the Okta service.

* Latest OpenAPI spec dist/current/
* [2024.06.1 Okta release](https://developer.okta.com/docs/release-notes/2024-okta-identity-engine/) (e.g. Latest/Current) OpenAPI spec [dist/2024.06.1/](dist/2024.06.1/)
* Historical Swagger spec [dist/legacy-v1-swagger/](dist/legacy-v1-swagger/)

Please open a support ticket at https://support.okta.com/ if you find one of the specs not working with your tooling to get help from a customer support engineer.
