### ISSUE TITLE
repo/specs status

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-management-openapi-spec#169]
1. will the readme be updated?
2. will the old swagger spec be maintained? for a while? will new endpoints end up in the old spec (eg `/devices`)?
3. will the new openapi spec be published in JSON as well as YAML? i fetch it from the browser which has native JSON support, but no native YAML support. i don't want to write/use a library to read YAML when i can use JSON.
4. is the new opeanpi spec ready to use?
5. will the old issues be addressed (including mine #155 )?

Thank you.

**Comment by monde** [comment]
This issue was filed against our old Swagger spec that we maintained by hand and has been deprecated. The Swagger spec will not be updated and I'll close this issue.

We do have OpenAPI v3 specs for Okta's Management API, OAuth API, and IDP / My Account API in the [dist/](dist/) directory. These specs are derived directly from internal sources used to build and run the Okta service.

* Latest OpenAPI spec dist/current/
* [2024.06.1 Okta release](https://developer.okta.com/docs/release-notes/2024-okta-identity-engine/) (e.g. Latest/Current) OpenAPI spec [dist/2024.06.1/](dist/2024.06.1/)
* Historical Swagger spec [dist/legacy-v1-swagger/](dist/legacy-v1-swagger/)

Please open a support ticket at https://support.okta.com/ if you find one of the specs not working with your tooling to get help from a customer support engineer.
