### ISSUE TITLE
Signed nonce missing from API spec 

### ISSUE THREAD

**Issue by wezham** [okta/okta-management-openapi-spec#174]
As noted in the docs [here](https://developer.okta.com/docs/reference/api/factors/#factor-type) - there exists a factor "signed_nonce". This is absent from the API spec in the latest release.

<img width="742" alt="Screen Shot 2023-07-16 at 4 52 18 pm" src="https://github.com/okta/okta-management-openapi-spec/assets/13143314/8b2fe257-ae46-48b5-963a-36f5d5f92315">

**Comment by monde** [comment]
This issue was filed against our old Swagger spec that we maintained by hand and has been deprecated. The Swagger spec will not be updated and I'll close this issue.

We do have OpenAPI v3 specs for Okta's Management API, OAuth API, and IDP / My Account API in the [dist/](dist/) directory. These specs are derived directly from internal sources used to build and run the Okta service.

* Latest OpenAPI spec dist/current/
* [2024.06.1 Okta release](https://developer.okta.com/docs/release-notes/2024-okta-identity-engine/) (e.g. Latest/Current) OpenAPI spec [dist/2024.06.1/](dist/2024.06.1/)
* Historical Swagger spec [dist/legacy-v1-swagger/](dist/legacy-v1-swagger/)

Please open a support ticket at https://support.okta.com/ if you find one of the specs not working with your tooling to get help from a customer support engineer.
