### ISSUE TITLE
Spec describing certain operations is inconsistent with API behavior 

### ISSUE THREAD

**Issue by krissirk** [okta/okta-management-openapi-spec#53]
I'd like to report an issue with the Okta OpenAPI 2.0 spec (version": "2.3.0") wherein the schema definition is inconsistent with the API response. 

An application my team has built codegen'd callouts to the API based on the spec cannot convert the "Mix of Object and Array type" additional properties returned from the response to "Object" type that the schema defined. A workaround of this is to remove "additionalProperties": { type: "object"}, from the schema definition if we encounter this kind of runtime incompatible error in the application. In this way, the additional properties returned from the response will be ignored, instead of trying to be converted to "object" type, and request-response application runtime based on a revised contract from the spec will succeed.

**Details**
Some of the Okta's operations (e.g. listAuthorizationServers, listApplications) reference response definition with additionalProperties of type "objects". Take listAuthorizationServers for example, see "_link" object definition screenshot in this screenshot:
![image](https://user-images.githubusercontent.com/8887394/126422286-89fe74e0-c57a-4591-be3b-268b1971ffc4.png)

However, the actual response returned from the server for "_link" is:
![image](https://user-images.githubusercontent.com/8887394/126422314-93e3353b-05fb-4ce3-aa62-837308787c17.png)

It has 8 additional properties, with 7 being HashMap but 1 called "metadata" being "ArrayList" type. Given that in the definition these additionalProperties are "object" type, an "Array" type property can't be resolved and marked as incompatible.

We request the official OpenAPI spec be revised to accurately represent the API behavior so we don't have to massage the JSON or YAML to workaround such inconsistencies.

**Comment by laura-rodriguez** [comment]
Hi @krissirk,

Thanks for reporting this issue!

I created an internal ticket and added it to our backlog to be prioritized by the team.

Internal Ref: OKTA-414196

**Comment by sergiishamrai-okta** [comment]
Thanks for your request @krissirk 

I've checked a swagger-codegen plugin that we use to generate Java SDK and I can say that the plugin uses `additionalProperties` property as a flag to describe that getter/setter in a target method should provide/accept a `Map<String, T>`.

In a case with an `AuthorizationServer` interface, the method will look like  `Map<String, Object> getLinks()`.

If we remove the `additionalProperties` from the openAPI spec, the method `getLinks()` will return an Object which is less declarative comparing to the existing one.

Describing each object under the _links section will lead to documentation enlargement and make this doc less readable.

Can you try to parse `_links` using `instanceof` operator so you will be sure whether the object is an instance of the `ArrayList` or `HashMap`?

**Comment by monde** [comment]
This issue was filed against our old Swagger spec that we maintained by hand and has been deprecated. The Swagger spec will not be updated and I'll close this issue.

We do have OpenAPI v3 specs for Okta's Management API, OAuth API, and IDP / My Account API in the [dist/](dist/) directory. These specs are derived directly from internal sources used to build and run the Okta service.

* Latest OpenAPI spec dist/current/
* [2024.06.1 Okta release](https://developer.okta.com/docs/release-notes/2024-okta-identity-engine/) (e.g. Latest/Current) OpenAPI spec [dist/2024.06.1/](dist/2024.06.1/)
* Historical Swagger spec [dist/legacy-v1-swagger/](dist/legacy-v1-swagger/)

Please open a support ticket at https://support.okta.com/ if you find one of the specs not working with your tooling to get help from a customer support engineer.
